#!/bin/bash
#PBS -n
#PBS -l walltime=3:00:00
#PBS -l nodes=1:ppn=3
#PBS -l mem=120gb
#PBS -o /home/scott.daniel/CellLocatorPrototype/VisualizationDraft/nrrd_${PBS_JOBID}_stdout.txt
#PBS -e /home/scott.daniel/CellLocatorPrototype/VisualizationDraft/nrrd_${PBS_JOBID}_stderr.txt
#PBS -q celltypes
#PBS -t 1-29


vis_dir=/home/scott.daniel/CellLocatorPrototype/VisualizationDraft/
cd ${vis_dir}
declare -i ii
ii=100*${PBS_ARRAYID}
ii=ii-100

echo ${ii}

python generate_nrrd.py \
--template average_template_10.nrrd \
--in_dir /allen/aibs/technology/danielsf/nick_dee_json_files/ \
--out_dir annotation_nrrd_nick_dee/ \
--n_threads 3 \
--istart ${ii} \
--lim 100
